#! /bin/bash
set -eu

set -x 


if [ "$1" = "por-defecto" ] ; then

 # reset workdir (brute force)

 rm -rf build
 mkdir -p build/dist

 # Comprueba la estructura de los datos
  yajsv -s pagina/datos.schema.yml pagina/por-defecto/contenido.yml
  yajsv -s pagina/diseno.schema.yml pagina/por-defecto/diseno.yml
  
  # Construye
  DATOS="pagina/por-defecto/contenido.yml"
  cat "$DATOS" | mustache - pagina/index.html.mustache > build/dist/index.html

  npx tailwindcss -i ./pagina/css/input.css -o ./build/dist/output.css &

fi

if [ "$1" = "subjecto" ] ; then
  # Recupera las rutas
  diseno=$(cat cursor.yml | yq .rutas.diseno)
  esteblog=$(cat cursor.yml | yq .rutas.esteblog)
  contenido=$(cat cursor.yml | yq .rutas.contenido)
  plantilla=blog


  # valida los datos intermedios
  # yajsv -s meta.schema.yml meta.yml
  # yajsv -s articulo.schema.yml articulo.yml
  

  # convercion del datos
  #conversion(){
  #  mustache meta.yml
  #}
  #datos=$( conversion )

  # Valida los datos final
  #yajsv -s datos.schema.yml datos.yml
  #yajsv -s diseno.schema.yml diseno.yml

  # construye
  # mustache datos.yml index.html.mustache
  

fi




