#! /bin/bash

dev()(
  set -eu -o pipefail
  local IMAGE_NAME=nous-image
  local CONTAINER_NAME=nous
  local SRC=$(realpath $(dirname ${BASH_SOURCE[0]}))

  _build(){
    docker build -t $IMAGE_NAME $SRC/.
  }

  _run(){
    local command=${1:-}
    docker run -d -v $SRC/:/src/ --name $CONTAINER_NAME $IMAGE_NAME $command 
  }

  sh_(){
	  echo "$@"
     [ "$(echo "$@" | wc -w)" = "0" ]\
	    && docker exec -it $CONTAINER_NAME sh  \
	    ||  eval "docker exec -it $CONTAINER_NAME sh -c \"$@\""
  }

  _stop(){
    docker stop $CONTAINER_NAME
  }

  _rm(){
    docker rm $CONTAINER_NAME
  }

  _rmi(){
    docker rmi $IMAGE_NAME
  }

  up(){
    _build || true
    _run   || true
  }

  down(){
    _stop || true
    _rm   || true
    _rmi  || true
  }
  
  case "${1:-}" in
    up) set -- up ${@:2} ;;
    down) set -- down ${@:2} ;;
    sh) set -- sh_ "${@:2}" ;;
    *) echo "command '${1:-}' not found" && exit 1 ;;
  esac

  $@

)

[ "${BASH_SOURCE[0]}" != "$0" ] || dev $@
